image: Ubuntu1804  # образ для сборки

stack: node 12  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

deploy_script:
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
